-- Create the ambassadors table
CREATE TABLE IF NOT EXISTS ambassadors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  photo_url TEXT NOT NULL,
  bio TEXT,
  social_links JSONB DEFAULT '[]'::jsonb,
  "order" INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE ambassadors ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Public can view ambassadors" 
ON ambassadors FOR SELECT 
TO public 
USING (true);

-- Create policy to allow authenticated admins to insert/update/delete
-- Note: Adjust 'authenticated' to specific roles if needed, currently allowing all authenticated for simplicity in this setup
CREATE POLICY "Admins can manage ambassadors" 
ON ambassadors FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

-- Verify table creation
SELECT * FROM ambassadors;
