create table if not exists public.featured_banners (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text not null,
  badge_text text not null default 'FEATURED EVENT',
  primary_button_text text not null,
  primary_button_link text not null,
  secondary_button_text text,
  secondary_button_link text,
  background_style text not null default 'red',
  image_url text,
  is_active boolean not null default false,
  "order" integer not null default 0,
  start_date timestamptz,
  end_date timestamptz,
  display_frequency text not null default 'every_visit',
  is_emergency boolean not null default false,
  show_countdown boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.featured_banners
  add column if not exists display_frequency text not null default 'every_visit',
  add column if not exists is_emergency boolean not null default false,
  add column if not exists show_countdown boolean not null default false;
alter table public.featured_banners
  add column if not exists image_url text;

insert into public.featured_banners (
  title,
  subtitle,
  badge_text,
  primary_button_text,
  primary_button_link,
  secondary_button_text,
  secondary_button_link,
  background_style,
  is_active,
  "order",
  display_frequency,
  is_emergency,
  show_countdown
)
select
  'NRSA National Interschool Championship 2026',
  '3 Zones • Delta • Ondo • Kwara — Registration Now Open',
  'REGISTRATION OPEN',
  'Register Your School',
  '/interschool/register',
  'Learn More',
  '/interschool',
  'red',
  true,
  0,
  'every_visit',
  true,
  true
where not exists (
  select 1 from public.featured_banners
  where title = 'NRSA National Interschool Championship 2026'
);

update public.featured_banners
set show_countdown = true
where title = 'NRSA National Interschool Championship 2026';

create table if not exists public.store_products (
  id bigint generated by default as identity primary key,
  name text not null,
  price integer not null default 0,
  image_url text,
  description text,
  is_preorder boolean not null default false,
  is_active boolean not null default false,
  "order" integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.featured_banners enable row level security;
alter table public.store_products enable row level security;

drop policy if exists "Public can read active featured banners" on public.featured_banners;
create policy "Public can read active featured banners"
  on public.featured_banners for select using (is_active = true);
drop policy if exists "Public can read active store products" on public.store_products;
create policy "Public can read active store products"
  on public.store_products for select using (is_active = true);
