-- NRSA Store order and payment foundation.
-- Run after supabase-featured-banner-store.sql and before/with supabase-rls-hardening.sql.

create table if not exists public.store_orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  delivery_address text,
  fulfillment_method text not null default 'pickup',
  amount integer not null check (amount >= 0),
  currency text not null default 'NGN',
  payment_status text not null default 'pending',
  fulfillment_status text not null default 'pending',
  paystack_reference text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.store_orders(id) on delete cascade,
  product_id bigint not null references public.store_products(id) on delete restrict,
  product_name text not null,
  unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now()
);

alter table public.store_orders enable row level security;
alter table public.store_order_items enable row level security;

-- Customers never read or modify orders directly. The Express service_role API
-- creates and updates them after validating payment server-side.
